import type { Metadata } from "next";
import { Libre_Caslon_Text } from "next/font/google";
import "./globals.css";

import RootLayoutShell from '../components/RootLayoutShell'; // Client component

const libre_caslon = Libre_Caslon_Text({
  weight: ["400", "700"],
  subsets: ["latin"],
  style: ["normal", "italic"],
  variable: '--font-libre_caslon',
});

export const metadata: Metadata = {
  title: "Welcome to Strøksnes",
  description: "Generated by Fran",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={libre_caslon.className}>
      <body>
        <RootLayoutShell>{children}</RootLayoutShell>
      </body>
    </html>
  );
}